services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    env_file:
      - .env 
    depends_on:
      - db
    networks:
      - regx-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - regx-network

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - regx-network

  adminer:
    image: adminer
    container_name: regx_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - regx-network

networks:
  regx-network:
    driver: bridge

volumes:
  postgres_data:
